# These are supported funding model platforms

github: [ Gokujo, ]
ko_fi: devcraft
custom: [ 'https://paypal.me/MaximH', 'https://yoomoney.ru/to/41001454367103', 'https://www.donationalerts.com/r/maharder']